[2025-09-09 21:53:10] [INFO    ] discord: Imagehash exists
[2025-09-09 21:53:10] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 21:53:10] [INFO    ] discord.client: logging in using static token
[2025-09-09 21:53:12] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9a2932bb78bf2c2092c8c9e91e2b364c).
[2025-09-09 21:53:52] [INFO    ] discord: Bot has started
[2025-09-09 21:53:53] [INFO    ] discord: Imagehash exists
[2025-09-09 21:53:53] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 21:53:53] [INFO    ] discord.client: logging in using static token
[2025-09-09 21:53:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 12b378bc7a16a4794b76ac61e91a4213).
[2025-09-09 21:53:57] [INFO    ] discord: 0.0005497932434082031
[2025-09-09 21:53:57] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-09 21:54:27] [INFO    ] discord: Bot has started
[2025-09-09 21:54:49] [INFO    ] discord: Imagehash exists
[2025-09-09 21:54:49] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 21:54:49] [INFO    ] discord.client: logging in using static token
[2025-09-09 21:54:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5f1ae6b803f924fc68f1f6b5eeecb999).
[2025-09-09 21:54:54] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 21:54:54] [INFO    ] discord: 0.0
[2025-09-09 21:54:54] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-09 21:55:39] [INFO    ] discord: Bot has started
[2025-09-09 21:55:41] [INFO    ] discord: Imagehash exists
[2025-09-09 21:55:41] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 21:55:41] [INFO    ] discord.client: logging in using static token
[2025-09-09 21:55:42] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 03d6adb1cf49c1c959b485f0aaa325da).
[2025-09-09 21:55:44] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 21:55:44] [INFO    ] discord: 0.0009982585906982422
[2025-09-09 21:55:44] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-09 21:55:46] [INFO    ] discord: Bot has started
[2025-09-09 22:05:24] [INFO    ] discord: Imagehash exists
[2025-09-09 22:05:24] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:05:24] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:05:27] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 17ec03e835ccb533d3517115d5a8bf3a).
[2025-09-09 22:05:29] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:05:29] [INFO    ] discord: 0.019539594650268555
[2025-09-09 22:05:29] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 55, in checkgunsmoke
    lastlaucnh = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:05:50] [INFO    ] discord: Bot has started
[2025-09-09 22:05:51] [INFO    ] discord: Imagehash exists
[2025-09-09 22:05:51] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:05:51] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:05:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 253b3fe2c6065ae98e69d6c0540f0a3c).
[2025-09-09 22:05:55] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:05:55] [INFO    ] discord: 0.00025963783264160156
[2025-09-09 22:05:55] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 51, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 42, in readjson
    Gunsmokecheck.writejson()
TypeError: Gunsmokecheck.writejson() missing 2 required positional arguments: 'datelastgunsmoke' and 'gunsmokeduration'
[2025-09-09 22:10:22] [INFO    ] discord: Bot has started
[2025-09-09 22:10:23] [INFO    ] discord: Imagehash exists
[2025-09-09 22:10:23] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:10:23] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:10:25] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c83cdaf481de969edcd77cf7b927540b).
[2025-09-09 22:10:27] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:10:27] [INFO    ] discord: 0.00022983551025390625
[2025-09-09 22:10:38] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 67, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 58, in readjson
    Gunsmokecheck.writejson(datetime.datetime(year, month, gusmokeduration),gusmokeduration)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer
[2025-09-09 22:11:19] [INFO    ] discord: Bot has started
[2025-09-09 22:11:21] [INFO    ] discord: Imagehash exists
[2025-09-09 22:11:21] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:11:21] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:11:23] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c1c97c0e8cb126296c01d703c232c61c).
[2025-09-09 22:11:25] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:11:25] [INFO    ] discord: 0.00023746490478515625
[2025-09-09 22:11:34] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 67, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 58, in readjson
    Gunsmokecheck.writejson(datetime.datetime(year, month, gusmokeduration),gusmokeduration)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer
[2025-09-09 22:11:55] [INFO    ] discord: Bot has started
[2025-09-09 22:12:35] [INFO    ] discord: Imagehash exists
[2025-09-09 22:12:35] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:12:35] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:12:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fd7a1bbf7aae7397555c91ac0bf89f4f).
[2025-09-09 22:12:40] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:12:40] [INFO    ] discord: 0.0010581016540527344
[2025-09-09 22:12:49] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 67, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 58, in readjson
    Gunsmokecheck.writejson(datetime.datetime(year, month, gusmokeduration),gusmokeduration)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer
[2025-09-09 22:13:17] [INFO    ] discord: Bot has started
[2025-09-09 22:15:13] [INFO    ] discord: Imagehash exists
[2025-09-09 22:15:13] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:15:13] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:15:20] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e0e95258c61aa1cca60509710efcc01f).
[2025-09-09 22:15:22] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:15:22] [INFO    ] discord: 0.0005199909210205078
[2025-09-09 22:15:36] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 61, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 52, in readjson
    Gunsmokecheck.writejson(date1,gusmokeduration)
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 16, in writejson
    if lastlaunch == None:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'lastlaunch' where it is not associated with a value
[2025-09-09 22:15:39] [INFO    ] discord: Bot has started
[2025-09-09 22:17:01] [INFO    ] discord: Imagehash exists
[2025-09-09 22:17:01] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:17:01] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:17:03] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7188d065cc1d292c9c1e71a5549a7868).
[2025-09-09 22:17:05] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:17:05] [INFO    ] discord: 0.0018949508666992188
[2025-09-09 22:17:11] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 64, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 55, in readjson
    Gunsmokecheck.writejson(date1,gusmokeduration)
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 20, in writejson
    "gunsmokeduration": gunsmokeduration,
                   ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'lastlaunch' where it is not associated with a value
[2025-09-09 22:17:13] [INFO    ] discord: Bot has started
[2025-09-09 22:17:26] [INFO    ] discord: Imagehash exists
[2025-09-09 22:17:26] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:17:26] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:17:27] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8e82fd8b51f80f1980e1361dbc67ae50).
[2025-09-09 22:17:29] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:17:29] [INFO    ] discord: 0.0004825592041015625
[2025-09-09 22:17:37] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 64, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 55, in readjson
    Gunsmokecheck.writejson(date1,gusmokeduration)
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 26, in writejson
    jsonObject = json.dumps(scheldue, default=json_util.default)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\bson\json_util.py", line 1048, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: datetime.date(2025, 9, 9) is not JSON serializable
[2025-09-09 22:17:39] [INFO    ] discord: Bot has started
[2025-09-09 22:18:21] [INFO    ] discord: Imagehash exists
[2025-09-09 22:18:21] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:18:21] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:18:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2088ba34107fc952082e2e383e04ae9d).
[2025-09-09 22:18:25] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:18:25] [INFO    ] discord: 0.001956462860107422
[2025-09-09 22:18:31] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 64, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 55, in readjson
    Gunsmokecheck.writejson(date1,gusmokeduration)
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 26, in writejson
    jsonObject = json.dumps(scheldue, default=json_util.default)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\bson\json_util.py", line 1048, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: <built-in method now of type object at 0x00007FFFDFC712B0> is not JSON serializable
[2025-09-09 22:18:38] [INFO    ] discord: Bot has started
[2025-09-09 22:20:26] [INFO    ] discord: Imagehash exists
[2025-09-09 22:20:26] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:20:26] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:20:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4f9c3795c0884eb7dafa2ac357d84b0e).
[2025-09-09 22:20:30] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:20:30] [INFO    ] discord: 0.0006184577941894531
[2025-09-09 22:20:35] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 63, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 48, in readjson
    year = int(input('Enter a year'))
               ^^^^^^^^^^^^^^^^^^^^^
EOFError
[2025-09-09 22:20:35] [INFO    ] discord: Bot has started
[2025-09-09 22:20:46] [INFO    ] discord: Imagehash exists
[2025-09-09 22:20:46] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:20:46] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:20:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 209ed51ec6bac5694d055a76f91b9fab).
[2025-09-09 22:20:50] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:20:50] [INFO    ] discord: 0.0008487701416015625
[2025-09-09 22:21:02] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 63, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 54, in readjson
    Gunsmokecheck.writejson(date1,gusmokeduration)
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 25, in writejson
    jsonObject = json.dumps(scheldue, default=json_util.default)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\bson\json_util.py", line 1048, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: datetime.date(2025, 9, 9) is not JSON serializable
[2025-09-09 22:21:10] [INFO    ] discord: Bot has started
[2025-09-09 22:21:59] [INFO    ] discord: Imagehash exists
[2025-09-09 22:21:59] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:21:59] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:22:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4e03332f59dfe4c48489e72380ab82a7).
[2025-09-09 22:22:03] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:22:03] [INFO    ] discord: 0.0015192031860351562
[2025-09-09 22:22:08] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 63, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 54, in readjson
    Gunsmokecheck.writejson(date1,gusmokeduration)
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 17, in writejson
    lastlaunch = datetime.datetime.isoformat()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unbound method datetime.isoformat() needs an argument
[2025-09-09 22:22:09] [INFO    ] discord: Bot has started
[2025-09-09 22:22:38] [INFO    ] discord: Imagehash exists
[2025-09-09 22:22:38] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:22:38] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:22:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a4eaf4293fce0ee5e588a3ed27fe3896).
[2025-09-09 22:22:42] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:22:42] [INFO    ] discord: 0.0010459423065185547
[2025-09-09 22:22:48] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 63, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 54, in readjson
    Gunsmokecheck.writejson(date1,gusmokeduration)
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 25, in writejson
    jsonObject = json.dumps(scheldue, default=json_util.default)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\bson\json_util.py", line 1048, in default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: datetime.date(2025, 9, 9) is not JSON serializable
[2025-09-09 22:22:51] [INFO    ] discord: Bot has started
[2025-09-09 22:24:20] [INFO    ] discord: Imagehash exists
[2025-09-09 22:24:20] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:24:20] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:24:21] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: cc9adce2ab40d29a3b6d9920c2a170c8).
[2025-09-09 22:24:23] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:24:23] [INFO    ] discord: 0.0009331703186035156
[2025-09-09 22:24:31] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 63, in checkgunsmoke
    lastgunsmoke = date["lastgunsmoke"]
                   ~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2025-09-09 22:26:48] [INFO    ] discord: Bot has started
[2025-09-09 22:26:49] [INFO    ] discord: Imagehash exists
[2025-09-09 22:26:49] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:26:49] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:26:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: adda0e38e1846b466d790b33215ab257).
[2025-09-09 22:26:54] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:26:54] [INFO    ] discord: 0.0
[2025-09-09 22:26:54] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 68, in checkgunsmoke
    lastlaucnh = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:26:56] [INFO    ] discord: Bot has started
[2025-09-09 22:27:24] [INFO    ] discord: Imagehash exists
[2025-09-09 22:27:24] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:27:24] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:27:26] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 977164a6de1b2b8767e222e1997fe163).
[2025-09-09 22:27:28] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:27:28] [INFO    ] discord: 0.002069234848022461
[2025-09-09 22:27:28] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 68, in checkgunsmoke
    lastlaucnh = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:29:10] [INFO    ] discord: Bot has started
[2025-09-09 22:29:11] [INFO    ] discord: Imagehash exists
[2025-09-09 22:29:11] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:29:11] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:29:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 04cb7d77caade8d4324af5034e378967).
[2025-09-09 22:29:16] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:29:16] [INFO    ] discord: 0.0005736351013183594
[2025-09-09 22:29:16] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:29:28] [INFO    ] discord: Bot has started
[2025-09-09 22:29:29] [INFO    ] discord: Imagehash exists
[2025-09-09 22:29:29] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:29:29] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:29:31] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: bee5ed066e269f705418460427bdb123).
[2025-09-09 22:29:33] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:29:33] [INFO    ] discord: 0.0005674362182617188
[2025-09-09 22:29:33] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunсh"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunсh'
[2025-09-09 22:29:36] [INFO    ] discord: Bot has started
[2025-09-09 22:30:29] [INFO    ] discord: Imagehash exists
[2025-09-09 22:30:29] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:30:29] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:30:32] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: dc681a1d9fff85baeed7a8b216f49b00).
[2025-09-09 22:30:34] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:30:34] [INFO    ] discord: 0.00032639503479003906
[2025-09-09 22:30:34] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunсh"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunсh'
[2025-09-09 22:30:43] [INFO    ] discord: Bot has started
[2025-09-09 22:30:49] [INFO    ] discord: Imagehash exists
[2025-09-09 22:30:49] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:30:49] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:30:51] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: da07411ecbd46383b50429d34c1c6fff).
[2025-09-09 22:30:53] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:30:53] [INFO    ] discord: 0.0007956027984619141
[2025-09-09 22:30:53] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:30:55] [INFO    ] discord: Bot has started
[2025-09-09 22:31:31] [INFO    ] discord: Imagehash exists
[2025-09-09 22:31:31] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:31:31] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:31:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: f897095d2137eef284f7cd159cd024c8).
[2025-09-09 22:31:36] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:31:36] [INFO    ] discord: 0.00096893310546875
[2025-09-09 22:31:36] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:31:39] [INFO    ] discord: Bot has started
[2025-09-09 22:32:59] [INFO    ] discord: Imagehash exists
[2025-09-09 22:32:59] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:32:59] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:33:00] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b3758cfe987c40225e9acb553ff32d29).
[2025-09-09 22:33:02] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:33:02] [INFO    ] discord: 0.0005164146423339844
[2025-09-09 22:33:03] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:33:09] [INFO    ] discord: Bot has started
[2025-09-09 22:33:36] [INFO    ] discord: Imagehash exists
[2025-09-09 22:33:36] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:33:36] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:33:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 553bd978969507cc16fe3b78df74e46a).
[2025-09-09 22:33:40] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:33:40] [INFO    ] discord: 0.0008876323699951172
[2025-09-09 22:33:40] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:33:59] [INFO    ] discord: Bot has started
[2025-09-09 22:36:06] [INFO    ] discord: Imagehash exists
[2025-09-09 22:36:06] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:36:06] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:36:10] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: db646854fb5898d4e03b963e7f4481d3).
[2025-09-09 22:36:12] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:36:12] [INFO    ] discord: 0.0007014274597167969
[2025-09-09 22:36:12] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    lastlaunch = date["lastlaunch"]
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lastlaunch'
[2025-09-09 22:36:23] [INFO    ] discord: Bot has started
[2025-09-09 22:37:02] [INFO    ] discord: Imagehash exists
[2025-09-09 22:37:02] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:37:02] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:37:04] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c97703776e04d23956cf47841be88b1c).
[2025-09-09 22:37:06] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:37:06] [INFO    ] discord: 0.0020143985748291016
[2025-09-09 22:37:55] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:38:05] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:38:15] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:38:25] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:38:35] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:38:45] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:38:55] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:39:05] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:39:15] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:39:25] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:39:35] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:39:45] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:39:55] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 130 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:40:05] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 140 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:40:15] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 150 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:40:25] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 160 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:40:35] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 170 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:40:45] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 180 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:40:55] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 190 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:41:05] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 200 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:41:15] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 210 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:41:25] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 220 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:41:35] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 230 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:41:45] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 240 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:41:55] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 250 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:42:05] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 260 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:42:15] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 270 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:42:25] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 280 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:42:35] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 290 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:42:45] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 300 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:42:55] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 310 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:43:05] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 320 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:43:15] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 330 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:43:25] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 340 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:43:35] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 350 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:43:45] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 360 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:43:55] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 370 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:44:05] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 380 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:44:15] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 390 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:44:25] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 400 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:44:35] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 410 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:44:45] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 420 seconds.
Loop thread traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\main.py", line 283, in <module>
    main()
  File "G:\Projects Big\Programming\Discord bot\main.py", line 278, in main
    client.run(TOKEN, log_handler=handler)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 897, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))

[2025-09-09 22:44:47] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 62, in checkgunsmoke
    date = Gunsmokecheck.readjson()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 49, in readjson
    year = int(input('Enter a year'))
               ^^^^^^^^^^^^^^^^^^^^^
EOFError
[2025-09-09 22:44:47] [INFO    ] discord: Bot has started
[2025-09-09 22:44:51] [INFO    ] discord: Imagehash exists
[2025-09-09 22:44:51] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:44:51] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:44:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6967ab6359f619ed247ad7200a349ab8).
[2025-09-09 22:45:01] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:45:01] [INFO    ] discord: 0.007987499237060547
[2025-09-09 22:45:07] [INFO    ] discord: None
[2025-09-09 22:45:50] [INFO    ] discord: Bot has started
[2025-09-09 22:47:29] [INFO    ] discord: Imagehash exists
[2025-09-09 22:47:29] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:47:29] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:47:32] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c704df11e7372038555714c4f9dc3e36).
[2025-09-09 22:47:34] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:47:34] [INFO    ] discord: 0.0020952224731445312
[2025-09-09 22:47:34] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 84, in checkgunsmoke
    elif timebetween.days() >= datetime.timedelta(days=7) and gunsmokeduration > 0 and lastlaunch != datenow.date():
        ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
[2025-09-09 22:47:40] [INFO    ] discord: Bot has started
[2025-09-09 22:48:37] [INFO    ] discord: Imagehash exists
[2025-09-09 22:48:37] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:48:37] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:48:38] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8243020077e756c551b128f120dbe5d5).
[2025-09-09 22:48:40] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:48:40] [INFO    ] discord: 0.0010836124420166016
[2025-09-09 22:48:40] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 68, in checkgunsmoke
    timebetween = datenow.days() - lastgunsmoke.days()
                  ^^^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute 'days'
[2025-09-09 22:48:42] [INFO    ] discord: Bot has started
[2025-09-09 22:48:48] [INFO    ] discord: Imagehash exists
[2025-09-09 22:48:48] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:48:48] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:48:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c498b8e971d6b4adcfd3521b7e46b766).
[2025-09-09 22:48:50] [INFO    ] discord: Bot has started
[2025-09-09 22:48:53] [INFO    ] discord: Imagehash exists
[2025-09-09 22:48:53] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:48:53] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:48:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a737f526a5086020dd7d77adb4590dfa).
[2025-09-09 22:48:57] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:48:57] [INFO    ] discord: 0.0006921291351318359
[2025-09-09 22:48:57] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 68, in checkgunsmoke
    timebetween = datenow.days() - lastgunsmoke
                  ^^^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute 'days'
[2025-09-09 22:50:25] [INFO    ] discord: Bot has started
[2025-09-09 22:50:26] [INFO    ] discord: Imagehash exists
[2025-09-09 22:50:26] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:50:26] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:50:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b841e5b6ad48fe7d3fee83848cca4a0a).
[2025-09-09 22:50:30] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:50:30] [INFO    ] discord: 0.0010845661163330078
[2025-09-09 22:50:30] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 79, in checkgunsmoke
    if daysbetween >= datetime.timedelta(days=7) and gunsmokeduration >= 7 and lastlaunch != datenow.date():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'int' and 'datetime.timedelta'
[2025-09-09 22:50:46] [INFO    ] discord: Bot has started
[2025-09-09 22:51:46] [INFO    ] discord: Imagehash exists
[2025-09-09 22:51:46] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:51:46] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:51:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ee8d2d5fe2be9904d42d3f756e8cc345).
[2025-09-09 22:51:50] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:51:50] [INFO    ] discord: 0.0014140605926513672
[2025-09-09 22:51:50] [INFO    ] discord: None
[2025-09-09 22:52:04] [INFO    ] discord: Bot has started
[2025-09-09 22:52:25] [INFO    ] discord: Imagehash exists
[2025-09-09 22:52:25] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:52:25] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:52:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e7af4a7a910063bfa6a1f85e7c770280).
[2025-09-09 22:52:30] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:52:30] [INFO    ] discord: 0.0005557537078857422
[2025-09-09 22:52:30] [INFO    ] discord: None
[2025-09-09 22:52:42] [INFO    ] discord: Bot has started
[2025-09-09 22:53:11] [INFO    ] discord: Imagehash exists
[2025-09-09 22:53:11] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:53:11] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:53:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 588d89110b7b876c0cb179d7830a6e54).
[2025-09-09 22:53:15] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:53:15] [INFO    ] discord: 0.0010030269622802734
[2025-09-09 22:53:15] [INFO    ] discord: None
[2025-09-09 22:53:19] [INFO    ] discord: Bot has started
[2025-09-09 22:53:25] [INFO    ] discord: Imagehash exists
[2025-09-09 22:53:25] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:53:25] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:53:27] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4a5bf066fa171488d0736b4b3c5ed172).
[2025-09-09 22:53:29] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:53:29] [INFO    ] discord: 0.0010342597961425781
[2025-09-09 22:53:37] [INFO    ] discord: None
[2025-09-09 22:54:26] [INFO    ] discord: Bot has started
[2025-09-09 22:55:29] [INFO    ] discord: Imagehash exists
[2025-09-09 22:55:29] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:55:29] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:55:31] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 00bed6110bfb93099feedd5a237cf1b5).
[2025-09-09 22:55:33] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:55:33] [INFO    ] discord: 0.0006618499755859375
[2025-09-09 22:55:33] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 79, in checkgunsmoke
    if timebetween >= datetime.timedelta(days=7) and gunsmokeduration >= 7 and lastlaunch != datenow.date():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'int' and 'datetime.timedelta'
[2025-09-09 22:57:03] [INFO    ] discord: Bot has started
[2025-09-09 22:58:16] [INFO    ] discord: Imagehash exists
[2025-09-09 22:58:16] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-09 22:58:16] [INFO    ] discord.client: logging in using static token
[2025-09-09 22:58:18] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ec0ac8f9d79be76a95e79b745470c23b).
[2025-09-09 22:58:20] [INFO    ] discord: We have logged as Helian#1038
[2025-09-09 22:58:20] [INFO    ] discord: 0.002604246139526367
[2025-09-09 22:58:20] [INFO    ] discord: None
[2025-09-09 22:58:46] [INFO    ] discord: Bot has started
[2025-09-10 00:29:08] [INFO    ] discord: Imagehash exists
[2025-09-10 00:29:08] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:29:08] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:29:11] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ae00dd167474385cc0f3176450a770aa).
[2025-09-10 00:29:13] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:29:13] [INFO    ] discord: 0.007524013519287109
[2025-09-10 00:29:13] [INFO    ] discord: None
[2025-09-10 00:29:19] [INFO    ] discord: Bot has started
[2025-09-10 00:29:54] [INFO    ] discord: Imagehash exists
[2025-09-10 00:29:54] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:29:54] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:29:56] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e36c9d15573f9ec8e524188f0e407106).
[2025-09-10 00:29:58] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:29:58] [INFO    ] discord: 0.0006415843963623047
[2025-09-10 00:29:58] [INFO    ] discord: None
[2025-09-10 00:30:27] [INFO    ] discord: Bot has started
[2025-09-10 00:32:15] [INFO    ] discord: Imagehash exists
[2025-09-10 00:32:15] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:32:15] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:32:18] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8874811d9759761a98e51a0c4dc4053f).
[2025-09-10 00:32:20] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:32:20] [INFO    ] discord: 0.000640869140625
[2025-09-10 00:32:20] [INFO    ] discord: None
[2025-09-10 00:32:29] [INFO    ] discord: Bot has started
[2025-09-10 00:48:48] [INFO    ] discord: Imagehash exists
[2025-09-10 00:48:48] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:48:48] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:48:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5e9d5abfea741dd95a93e299f0890122).
[2025-09-10 00:48:57] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:48:58] [INFO    ] discord: 0.202650785446167
[2025-09-10 00:48:58] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    daysincelastlaunch = (datenow.date() - lastgunsmoke.day()).days
                                           ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
[2025-09-10 00:49:03] [INFO    ] discord: Bot has started
[2025-09-10 00:49:15] [INFO    ] discord: Imagehash exists
[2025-09-10 00:49:15] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:49:15] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:49:19] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8aeb72efab58c3a4662586ed205b4f57).
[2025-09-10 00:49:21] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:49:21] [INFO    ] discord: 0.0009491443634033203
[2025-09-10 00:49:21] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    daysincelastlaunch = (datenow.date() - lastgunsmoke).days
                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'
[2025-09-10 00:49:32] [INFO    ] discord: Bot has started
[2025-09-10 00:49:34] [INFO    ] discord: Imagehash exists
[2025-09-10 00:49:34] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:49:34] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:49:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5f3773ac9a096fe6532c1e5ae5a80929).
[2025-09-10 00:49:37] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:49:37] [INFO    ] discord: 0.0
[2025-09-10 00:49:37] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    daysincelastlaunch = (datenow.date() - lastgunsmoke).days()
                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.date' and 'datetime.datetime'
[2025-09-10 00:49:42] [INFO    ] discord: Bot has started
[2025-09-10 00:49:58] [INFO    ] discord: Imagehash exists
[2025-09-10 00:49:58] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:49:58] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:50:00] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 736a7a67a0255cdc056e72485af3803d).
[2025-09-10 00:50:02] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:50:02] [INFO    ] discord: 0.0
[2025-09-10 00:50:02] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    daysincelastlaunch = (datenow.date() - lastgunsmoke.days())
                                           ^^^^^^^^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute 'days'
[2025-09-10 00:50:10] [INFO    ] discord: Bot has started
[2025-09-10 00:50:11] [INFO    ] discord: Imagehash exists
[2025-09-10 00:50:11] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:50:11] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:50:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 02127b2e71cc864d6d2d916dd28d5005).
[2025-09-10 00:50:15] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:50:15] [INFO    ] discord: 0.0006973743438720703
[2025-09-10 00:50:15] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    daysincelastlaunch = (datenow.date() - lastgunsmoke.date()).days()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
[2025-09-10 00:50:18] [INFO    ] discord: Bot has started
[2025-09-10 00:50:35] [INFO    ] discord: Imagehash exists
[2025-09-10 00:50:35] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:50:35] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:50:37] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ad4f77ba9b9e7eefd47b7dc338dbb438).
[2025-09-10 00:50:40] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:50:40] [INFO    ] discord: 0.00106048583984375
[2025-09-10 00:50:40] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 66, in checkgunsmoke
    daysincelastlaunch = (datenow.date() - lastgunsmoke.date()).days
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
[2025-09-10 00:50:41] [INFO    ] discord: Bot has started
[2025-09-10 00:50:44] [INFO    ] discord: Imagehash exists
[2025-09-10 00:50:44] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:50:44] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:50:45] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 85a443f424a75083301ac96020064308).
[2025-09-10 00:50:47] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:50:47] [INFO    ] discord: 0.0009202957153320312
[2025-09-10 00:50:47] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 78, in checkgunsmoke
    if gunsmokeduration > 0 and lastlaunch != datenow.date():
       ^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
[2025-09-10 00:50:52] [INFO    ] discord: Bot has started
[2025-09-10 00:52:31] [INFO    ] discord: Imagehash exists
[2025-09-10 00:52:31] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:52:31] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:52:33] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c6cf2c7d03d47b290dd6aa0ed698b203).
[2025-09-10 00:52:35] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:52:35] [INFO    ] discord: 0.0007569789886474609
[2025-09-10 00:52:35] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 00:52:50] [INFO    ] discord: Bot has started
[2025-09-10 00:53:34] [INFO    ] discord: Imagehash exists
[2025-09-10 00:53:34] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:53:34] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:53:36] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 237f6a3a8833a02253a96a4b43c0a68c).
[2025-09-10 00:53:38] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:53:39] [INFO    ] discord: 0.0004131793975830078
[2025-09-10 00:53:39] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 00:54:09] [INFO    ] discord: Bot has started
[2025-09-10 00:54:11] [INFO    ] discord: Imagehash exists
[2025-09-10 00:54:11] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:54:11] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:54:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 42201b161732822f875c89dcec36ec2d).
[2025-09-10 00:54:15] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:54:15] [INFO    ] discord: 0.000985860824584961
[2025-09-10 00:54:15] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 00:54:20] [INFO    ] discord: Bot has started
[2025-09-10 00:58:01] [INFO    ] discord: Imagehash exists
[2025-09-10 00:58:01] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:58:01] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:58:02] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 97c9748182053d225859c0f276dc75f6).
[2025-09-10 00:58:05] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:58:05] [INFO    ] discord: 0.0022263526916503906
[2025-09-10 00:58:05] [INFO    ] discord: None
[2025-09-10 00:58:09] [INFO    ] discord: Bot has started
[2025-09-10 00:58:19] [INFO    ] discord: Imagehash exists
[2025-09-10 00:58:19] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:58:19] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:58:20] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a1c8421e3d2a5619cbb169416055fcaf).
[2025-09-10 00:58:22] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:58:22] [INFO    ] discord: 0.0006842613220214844
[2025-09-10 00:58:22] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 00:58:27] [INFO    ] discord: Bot has started
[2025-09-10 00:58:28] [INFO    ] discord: Imagehash exists
[2025-09-10 00:58:28] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 00:58:28] [INFO    ] discord.client: logging in using static token
[2025-09-10 00:58:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b0ce4c357c8b6903a1be2df9d6458460).
[2025-09-10 00:58:32] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 00:58:32] [INFO    ] discord: 0.000926971435546875
[2025-09-10 00:58:32] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 00:58:37] [INFO    ] discord: Bot has started
[2025-09-10 01:00:30] [INFO    ] discord: Imagehash exists
[2025-09-10 01:00:30] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:00:30] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:00:33] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fed9cb05e3b5501ebf50be2e17bd1cfd).
[2025-09-10 01:00:35] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:00:35] [INFO    ] discord: 0.0
[2025-09-10 01:00:35] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 220, in on_ready
    gunsmokeanswers = Gunsmoke.Gunsmokecheck.checkgunsmoke()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects Big\Programming\Discord bot\Gunsmoke.py", line 58, in checkgunsmoke
    datenow = datetime.datetime.date()
              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unbound method datetime.date() needs an argument
[2025-09-10 01:00:39] [INFO    ] discord: Bot has started
[2025-09-10 01:00:51] [INFO    ] discord: Imagehash exists
[2025-09-10 01:00:51] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:00:51] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:00:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ce9bc01f273389013520362bbd3473bf).
[2025-09-10 01:00:55] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:00:55] [INFO    ] discord: 0.0
[2025-09-10 01:00:55] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 01:00:58] [INFO    ] discord: Bot has started
[2025-09-10 01:01:07] [INFO    ] discord: Imagehash exists
[2025-09-10 01:01:07] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:01:07] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:01:09] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 05a5e148dbc6cf5e6657b6d3690e4bc5).
[2025-09-10 01:01:11] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:01:11] [INFO    ] discord: 0.0
[2025-09-10 01:01:11] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 01:01:20] [INFO    ] discord: Bot has started
[2025-09-10 01:01:31] [INFO    ] discord: Imagehash exists
[2025-09-10 01:01:31] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:01:31] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:01:33] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b63c42db0fdf0e5855b0a5646f0cc9ed).
[2025-09-10 01:01:35] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:01:35] [INFO    ] discord: 0.000507354736328125
[2025-09-10 01:01:35] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 01:01:42] [INFO    ] discord: Bot has started
[2025-09-10 01:01:43] [INFO    ] discord: Imagehash exists
[2025-09-10 01:01:43] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:01:43] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:01:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: aa7415713c6c8a74eaedc6a8fa79bbf1).
[2025-09-10 01:01:47] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:01:47] [INFO    ] discord: 0.000659942626953125
[2025-09-10 01:01:47] [INFO    ] discord: Gunsmoke time! 🚨🚬 
Do not forget go on boss-battle
[2025-09-10 01:01:52] [INFO    ] discord: Bot has started
[2025-09-10 01:13:14] [INFO    ] discord: Imagehash exists
[2025-09-10 01:13:14] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:13:14] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:13:23] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c7d927b587e8d703cb5d525d5acc3f8a).
[2025-09-10 01:13:25] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:13:25] [INFO    ] discord: 0.0032944679260253906
[2025-09-10 01:13:25] [INFO    ] discord: None
[2025-09-10 01:21:11] [INFO    ] discord: Bot has started
[2025-09-10 01:22:58] [INFO    ] discord: Imagehash exists
[2025-09-10 01:22:58] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:22:58] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:23:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7671950e07cda701d037aca9510712c3).
[2025-09-10 01:23:03] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:23:03] [INFO    ] discord: 0.009358644485473633
[2025-09-10 01:23:03] [INFO    ] discord: None
[2025-09-10 01:24:26] [INFO    ] discord: Bot has started
[2025-09-10 01:33:51] [INFO    ] discord: Imagehash exists
[2025-09-10 01:33:51] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:33:51] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:33:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 32f92a97b2175e21cd8e093538bea9e7).
[2025-09-10 01:34:01] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:34:01] [INFO    ] discord: 0.0043752193450927734
[2025-09-10 01:34:01] [INFO    ] discord: None
[2025-09-10 01:34:29] [INFO    ] discord: Bot has started
[2025-09-10 01:34:34] [INFO    ] discord: Imagehash exists
[2025-09-10 01:34:34] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:34:34] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:34:37] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 264f507a0a2e3ed48119a286f235451e).
[2025-09-10 01:34:39] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:34:39] [INFO    ] discord: 0.0009982585906982422
[2025-09-10 01:34:39] [INFO    ] discord: None
[2025-09-10 01:37:47] [INFO    ] discord: Bot has started
[2025-09-10 01:37:58] [INFO    ] discord: Imagehash exists
[2025-09-10 01:37:58] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:37:58] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:38:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: da0961225e09b12cd131c5497ea987a8).
[2025-09-10 01:38:03] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:38:03] [INFO    ] discord: 0.0
[2025-09-10 01:38:03] [INFO    ] discord: None
[2025-09-10 01:38:24] [INFO    ] discord: Bot has started
[2025-09-10 01:47:13] [INFO    ] discord: Imagehash exists
[2025-09-10 01:47:13] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:47:13] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:47:16] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c869561ea8e1c4362c1569b5c9bee4d7).
[2025-09-10 01:47:18] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:47:18] [INFO    ] discord: 0.0030002593994140625
[2025-09-10 01:47:18] [INFO    ] discord: None
[2025-09-10 01:47:19] [INFO    ] discord: Bot has started
[2025-09-10 01:47:55] [INFO    ] discord: Imagehash exists
[2025-09-10 01:47:55] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:47:55] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:47:57] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 58d2ca2f98a9dcf99f0e7c4559d977fd).
[2025-09-10 01:47:59] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:47:59] [INFO    ] discord: 0.0006597042083740234
[2025-09-10 01:47:59] [INFO    ] discord: None
[2025-09-10 01:48:02] [INFO    ] discord: Bot has started
[2025-09-10 01:50:31] [INFO    ] discord: Imagehash exists
[2025-09-10 01:50:31] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 01:50:31] [INFO    ] discord.client: logging in using static token
[2025-09-10 01:50:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 18c606e05889dfc6c523bb409065428d).
[2025-09-10 01:50:36] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 01:50:36] [INFO    ] discord: 0.0
[2025-09-10 01:50:36] [INFO    ] discord: None
[2025-09-10 01:51:21] [INFO    ] discord: Bot has started
[2025-09-10 02:17:56] [INFO    ] discord: Imagehash exists
[2025-09-10 02:17:56] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:17:56] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:17:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e56215d9766f48188e606e2207ca73b6).
[2025-09-10 02:18:01] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:18:01] [INFO    ] discord: 0.01518869400024414
[2025-09-10 02:18:01] [INFO    ] discord: None
[2025-09-10 02:18:17] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 243, in on_message
    if previousmsgs["content"] != message.content:
       ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-09-10 02:18:18] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 243, in on_message
    if previousmsgs["content"] != message.content:
       ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-09-10 02:18:21] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 243, in on_message
    if previousmsgs["content"] != message.content:
       ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-09-10 02:18:24] [INFO    ] discord: Bot has started
[2025-09-10 02:18:51] [INFO    ] discord: Imagehash exists
[2025-09-10 02:18:51] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:18:51] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:18:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ad4a475eadb101258f454fa9151f0871).
[2025-09-10 02:18:55] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:18:55] [INFO    ] discord: 0.0
[2025-09-10 02:18:55] [INFO    ] discord: None
[2025-09-10 02:19:06] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 242, in on_message
    if previousmsgs["content"] != message.content:
       ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-09-10 02:19:07] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 242, in on_message
    if previousmsgs["content"] != message.content:
       ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-09-10 02:19:08] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 242, in on_message
    if previousmsgs["content"] != message.content:
       ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-09-10 02:19:10] [INFO    ] discord: Bot has started
[2025-09-10 02:23:21] [INFO    ] discord: Imagehash exists
[2025-09-10 02:23:21] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:23:21] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:23:24] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4930ffb01ccc162d9c946768a87f0642).
[2025-09-10 02:23:26] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:23:26] [INFO    ] discord: 0.02293705940246582
[2025-09-10 02:23:26] [INFO    ] discord: None
[2025-09-10 02:23:35] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 240, in on_message
    if previousmsgs["content"] != message.content:
       ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-09-10 02:23:41] [INFO    ] discord: Bot has started
[2025-09-10 02:38:05] [INFO    ] discord: Imagehash exists
[2025-09-10 02:38:05] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:38:05] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:38:12] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a1d1841cd5c5d2a69399428a1a2c4ca2).
[2025-09-10 02:38:14] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:38:14] [INFO    ] discord: 0.01882457733154297
[2025-09-10 02:38:14] [INFO    ] discord: None
[2025-09-10 02:38:28] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 242, in on_message
    channel_id = message.channel_id
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'channel_id'
[2025-09-10 02:38:30] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 242, in on_message
    channel_id = message.channel_id
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'channel_id'
[2025-09-10 02:38:31] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 242, in on_message
    channel_id = message.channel_id
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'channel_id'
[2025-09-10 02:40:08] [INFO    ] discord: Bot has started
[2025-09-10 02:40:09] [INFO    ] discord: Imagehash exists
[2025-09-10 02:40:09] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:40:09] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:40:11] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ba2b4e523c19b8f9c4d97affd41144f7).
[2025-09-10 02:40:13] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:40:13] [INFO    ] discord: 0.0009987354278564453
[2025-09-10 02:40:13] [INFO    ] discord: None
[2025-09-10 02:40:16] [INFO    ] discord: error in appending message
[2025-09-10 02:40:18] [INFO    ] discord: error in appending message
[2025-09-10 02:40:21] [INFO    ] discord: error in appending message
[2025-09-10 02:40:21] [INFO    ] discord: Count has 3
[2025-09-10 02:40:21] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "G:\Projects Big\Programming\Discord bot\venv\Lib\site-packages\discord\client.py", line 472, in _run_event
    await coro(*args, **kwargs)
  File "G:\Projects Big\Programming\Discord bot\main.py", line 255, in on_message
    await message.replay(content, mention_author = False)
          ^^^^^^^^^^^^^^
AttributeError: 'Message' object has no attribute 'replay'
[2025-09-10 02:40:47] [INFO    ] discord: Bot has started
[2025-09-10 02:41:05] [INFO    ] discord: Imagehash exists
[2025-09-10 02:41:05] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:41:05] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:41:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4dcd748606b27733d5c627d457ac768c).
[2025-09-10 02:41:09] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:41:09] [INFO    ] discord: 0.0005273818969726562
[2025-09-10 02:41:09] [INFO    ] discord: None
[2025-09-10 02:41:16] [INFO    ] discord: error in appending message
[2025-09-10 02:41:17] [INFO    ] discord: error in appending message
[2025-09-10 02:41:18] [INFO    ] discord: error in appending message
[2025-09-10 02:41:18] [INFO    ] discord: Count has 3
[2025-09-10 02:41:18] [INFO    ] discord: Deleting images
[2025-09-10 02:41:30] [INFO    ] discord: Bot has started
[2025-09-10 02:41:34] [INFO    ] discord: Imagehash exists
[2025-09-10 02:41:34] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:41:34] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:41:36] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0f7bd9275afdc6a9a3cb5ec673803e1e).
[2025-09-10 02:41:38] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:41:38] [INFO    ] discord: 0.0005300045013427734
[2025-09-10 02:41:38] [INFO    ] discord: None
[2025-09-10 02:41:39] [INFO    ] discord: error in appending message
[2025-09-10 02:41:43] [INFO    ] discord: error in appending message
[2025-09-10 02:41:44] [INFO    ] discord: error in appending message
[2025-09-10 02:41:44] [INFO    ] discord: Count has 3
[2025-09-10 02:41:44] [INFO    ] discord: Deleting images
[2025-09-10 02:42:03] [INFO    ] discord: Bot has started
[2025-09-10 02:48:31] [INFO    ] discord: Imagehash exists
[2025-09-10 02:48:31] [WARNING ] discord.client: PyNaCl is not installed, voice will NOT be supported
[2025-09-10 02:48:31] [INFO    ] discord.client: logging in using static token
[2025-09-10 02:48:35] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 89e59d73c7193d36f8361496c5c9d28e).
[2025-09-10 02:48:37] [INFO    ] discord: We have logged as Helian#1038
[2025-09-10 02:48:37] [INFO    ] discord: 0.013714075088500977
[2025-09-10 02:48:37] [INFO    ] discord: None
[2025-09-10 02:48:46] [INFO    ] discord: message was appending
[2025-09-10 02:48:56] [INFO    ] discord: Bot has started
